name: Build and Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.2

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: |
          pnpm lint
          pnpm prettier

      - name: Test
        run: npm test

      - name: Build all
        run: |
          pnpm build:cjs
          pnpm build:esm
          pnpm build:types

      # - name: Publish
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
